# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rate_m_cpp <- function(state, params, maleTypePrefix) {
    .Call('debugIIT_rate_m_cpp', PACKAGE = 'debugIIT', state, params, maleTypePrefix)
}

rate_f_cpp <- function(state, params, femaleTypePrefix, mateTypeSuffix, allMateTypes) {
    .Call('debugIIT_rate_f_cpp', PACKAGE = 'debugIIT', state, params, femaleTypePrefix, mateTypeSuffix, allMateTypes)
}

rate_imm_cpp <- function(state, params, immatureType, immatureClassNumber, allImmatureTypes) {
    .Call('debugIIT_rate_imm_cpp', PACKAGE = 'debugIIT', state, params, immatureType, immatureClassNumber, allImmatureTypes)
}

getRates_cpp <- function(state, params, allPrefixTypes) {
    .Call('debugIIT_getRates_cpp', PACKAGE = 'debugIIT', state, params, allPrefixTypes)
}

simulateCTMC_cpp <- function(R_state, R_types, R_params, R_startTime, R_endTime, maxSize, store = TRUE) {
    .Call('debugIIT_simulateCTMC_cpp', PACKAGE = 'debugIIT', R_state, R_types, R_params, R_startTime, R_endTime, maxSize, store)
}

